require('babel-polyfill');
require('./dum-core/dum');
require('./dum-core/router');
require('./dum-core/factories/service');
require('./dum-core/factories/component');
require('./dum-core/elements');
require('./dum-core/config');
require('./examples/config');
require('./examples/routes');
